export const GET_TECHNOLOGIES ='GET_TECHNOLOGIES'
export const ADD_TECHNOLOGY ='ADD_TECHNOLOGY'
export const DELETE_TECHNOLOGY ='DELETE_TECHNOLOGY'

export const GET_PACKAGES ='GET_PACKAGES'
export const ADD_PACKAGE ='ADD_PACKAGE'
export const DELETE_PACKAGE ='DELETE_PACKAGE'
