// INITIALIZE_TECHNOLOGIES
export const INITIALIZE_TECHNOLOGIES = "INITIALIZE_TECHNOLOGIES";
export const INITIALIZE_TECHNOLOGIES_PENDING = "INITIALIZE_TECHNOLOGIES_PENDING";
export const INITIALIZE_TECHNOLOGIES_FULFILLED = "INITIALIZE_TECHNOLOGIES_FULFILLED";
export const INITIALIZE_TECHNOLOGIES_REJECTED = "INITIALIZE_TECHNOLOGIES_REJECTED";

// FETCH_PACKAGES
export const FETCH_PACKAGES = "FETCH_PACKAGES";
export const FETCH_PACKAGES_PENDING = "FETCH_PACKAGES_PENDING";
export const FETCH_PACKAGES_FULFILLED = "FETCH_PACKAGES_FULFILLED";
export const FETCH_PACKAGES_REJECTED = "FETCH_PACKAGES_REJECTED";


